import typing
from dataclasses import dataclass

import typing_extensions
from flytekit.core.annotation import FlyteAnnotation
from latch.types.directory import LatchDir, LatchOutputDir
from latch.types.file import LatchFile
from latch.types.metadata import (
    Fork,
    ForkBranch,
    LatchAuthor,
    NextflowMetadata,
    NextflowParameter,
    NextflowRuntimeResources,
    Params,
    Section,
    Spoiler,
    Text,
)

flow = [
    Section(
        "Input/Output Options",
        Params(
            "input",
            "outdir",
            "email",
            "multiqc_title",
            "build_references",
            "cosmic_username",
            "cosmic_passwd",
            "genomes_base",
            "ensembl_version",
            "starfusion_build",
            "read_length",
        ),
    ),
    Section(
        "Analysis Options",
        Params(
            "all",
            "arriba",
            "fusioncatcher",
            "fusioninspector_only",
            "fusionreport",
            "qiagen",
            "starfusion",
            "starindex",
            "stringtie",
            "tools_cutoff",
        ),
    ),
    Section(
        "Reference Files",
        Params(
            "arriba_ref",
            "arriba_ref_blacklist",
            "arriba_ref_cytobands",
            "arriba_ref_known_fusions",
            "arriba_ref_protein_domains",
            "ensembl_ref",
            "fusioncatcher_ref",
            "fusionreport_ref",
            "hgnc_ref",
            "hgnc_date",
            "starfusion_ref",
            "starindex_ref",
        ),
    ),
    Section(
        "Output Files",
        Params(
            "arriba_fusions",
            "fusioncatcher_fusions",
            "fusioninspector_fusions",
            "starfusion_fusions",
            "whitelist",
        ),
    ),
    Section(
        "Tool-specific Options",
        Params(
            "fusioncatcher_limitSjdbInsertNsj",
            "fusioninspector_limitSjdbInsertNsj",
        ),
    ),
    Section(
        "Read Trimming Options",
        Params(
            "fastp_trim",
            "trim_tail",
            "adapter_fasta",
        ),
    ),
    Section(
        "Alignment Options",
        Params(
            "cram",
        ),
    ),
    Section(
        "Reference Genome Options",
        Params(
            "genome",
            "fasta",
            "fai",
            "gtf",
            "chrgtf",
            "transcript",
            "refflat",
            "rrna_intervals",
        ),
    ),
    Section(
        "QC and Visualization",
        Params(
            "skip_qc",
            "skip_vis",
            "multiqc_methods_description",
        ),
    ),
]

generated_parameters = {
    "input": NextflowParameter(
        type=typing.Optional[LatchFile],
        display_name="Input CSV",
        default=None,
        description="Path to comma-separated file containing information about the samples in the experiment.",
    ),
    "outdir": NextflowParameter(
        type=LatchOutputDir,
        display_name="Output Directory",
        default=None,
        description="The output directory where the results will be saved.",
    ),
    "email": NextflowParameter(
        type=typing.Optional[str],
        display_name="Email",
        default=None,
        description="Email address for completion summary.",
    ),
    "multiqc_title": NextflowParameter(
        type=typing.Optional[str],
        display_name="MultiQC Report Title",
        default=None,
        description="MultiQC report title. Printed as page header, used for filename if not otherwise specified.",
    ),
    "build_references": NextflowParameter(
        type=bool,
        display_name="Build References",
        default=None,
        description="Specifies which analysis type for the pipeline - either build references or analyse data",
    ),
    "cosmic_username": NextflowParameter(
        type=typing.Optional[str],
        display_name="COSMIC Username",
        default=None,
        description="COSMIC username",
    ),
    "cosmic_passwd": NextflowParameter(
        type=typing.Optional[str],
        display_name="COSMIC Password",
        default=None,
        description="COSMIC password",
    ),
    "genomes_base": NextflowParameter(
        type=str,
        display_name="Genomes Base Path",
        default=None,
        description="Path to reference folder",
    ),
    "ensembl_version": NextflowParameter(
        type=typing.Optional[int],
        display_name="Ensembl Version",
        default=102,
        description="ensembl version",
    ),
    "starfusion_build": NextflowParameter(
        type=bool,
        display_name="Build STAR-Fusion References",
        default=None,
        description="If set, starfusion references are built from scratch instead of downloaded (default)",
    ),
    "read_length": NextflowParameter(
        type=typing.Optional[int],
        display_name="Read Length",
        default=100,
        description="Read length",
    ),
    "all": NextflowParameter(
        type=bool,
        display_name="Run All Analyses",
        default=None,
        description="Build or run all references/analyses",
    ),
    "arriba": NextflowParameter(
        type=bool,
        display_name="Run Arriba",
        default=None,
        description="Build or run arriba references/analyses",
    ),
    "arriba_ref": NextflowParameter(
        type=typing.Optional[str],
        display_name="Arriba References",
        default=None,
        description="Path to arriba references",
    ),
    "arriba_ref_blacklist": NextflowParameter(
        type=typing.Optional[str],
        display_name="Arriba Blacklist",
        default=None,
        description="Path to arriba reference blacklist",
    ),
    "arriba_ref_cytobands": NextflowParameter(
        type=typing.Optional[str],
        display_name="Arriba Cytobands",
        default=None,
        description="Path to arriba reference cytobands",
    ),
    "arriba_ref_known_fusions": NextflowParameter(
        type=typing.Optional[str],
        display_name="Arriba Known Fusions",
        default=None,
        description="Path to arriba reference known fusions",
    ),
    "arriba_ref_protein_domains": NextflowParameter(
        type=typing.Optional[str],
        display_name="Arriba Protein Domains",
        default=None,
        description="Path to arriba reference protein domain",
    ),
    "arriba_fusions": NextflowParameter(
        type=typing.Optional[str],
        display_name="Arriba Fusions Output",
        default=None,
        description="Path to arriba output",
    ),
    "ensembl_ref": NextflowParameter(
        type=typing.Optional[str],
        display_name="Ensembl References",
        default=None,
        description="Path to ensembl references",
    ),
    "fusioncatcher": NextflowParameter(
        type=bool,
        display_name="Run FusionCatcher",
        default=None,
        description="Build or run fusioncatcher references/analyses",
    ),
    "fusioncatcher_fusions": NextflowParameter(
        type=typing.Optional[str],
        display_name="FusionCatcher Fusions Output",
        default=None,
        description="Path to fusioncatcher output",
    ),
    "fusioncatcher_limitSjdbInsertNsj": NextflowParameter(
        type=typing.Optional[int],
        display_name="FusionCatcher limitSjdbInsertNsj",
        default=None,
        description="Use limitSjdbInsertNsj with int for fusioncatcher",
    ),
    "fusioncatcher_ref": NextflowParameter(
        type=typing.Optional[str],
        display_name="FusionCatcher References",
        default=None,
        description="Path to fusioncatcher references",
    ),
    "fusioninspector_limitSjdbInsertNsj": NextflowParameter(
        type=typing.Optional[int],
        display_name="FusionInspector limitSjdbInsertNsj",
        default=None,
        description="Use limitSjdbInsertNsj with int for fusioninspector STAR process",
    ),
    "fusioninspector_only": NextflowParameter(
        type=bool,
        display_name="Run FusionInspector Only",
        default=None,
        description="Skip fusion-report. --fusioninspector_fusions PATH needed to provide a fusion list as input",
    ),
    "fusioninspector_fusions": NextflowParameter(
        type=typing.Optional[str],
        display_name="FusionInspector Fusions Input",
        default=None,
        description="Path to a fusion list file built with format GENE1--GENE2",
    ),
    "fusionreport": NextflowParameter(
        type=bool,
        display_name="Build Fusion Report",
        default=None,
        description="Build fusionreport references",
    ),
    "fusionreport_ref": NextflowParameter(
        type=typing.Optional[str],
        display_name="Fusion Report References",
        default=None,
        description="Path to fusionreport references",
    ),
    "hgnc_ref": NextflowParameter(
        type=typing.Optional[str],
        display_name="HGNC Database",
        default=None,
        description="Path to HGNC database file",
    ),
    "hgnc_date": NextflowParameter(
        type=typing.Optional[str],
        display_name="HGNC Timestamp",
        default=None,
        description="Path to HGNC timestamp file for database retrieval",
    ),
    "qiagen": NextflowParameter(
        type=bool,
        display_name="Use QIAGEN COSMIC",
        default=None,
        description="Use QIAGEN instead of SANGER to download COSMIC database",
    ),
    "starfusion": NextflowParameter(
        type=bool,
        display_name="Run STAR-Fusion",
        default=None,
        description="Build or run starfusion references/analyses",
    ),
    "starfusion_fusions": NextflowParameter(
        type=typing.Optional[str],
        display_name="STAR-Fusion Output",
        default=None,
        description="Path to starfusion output",
    ),
    "starfusion_ref": NextflowParameter(
        type=typing.Optional[str],
        display_name="STAR-Fusion References",
        default=None,
        description="Path to starfusion references",
    ),
    "starindex": NextflowParameter(
        type=bool,
        display_name="Run STAR Index",
        default=None,
        description="Build or run starindex references/analyses",
    ),
    "starindex_ref": NextflowParameter(
        type=typing.Optional[str],
        display_name="STAR Index References",
        default=None,
        description="Path to starindex references",
    ),
    "stringtie": NextflowParameter(
        type=bool,
        display_name="Run StringTie",
        default=None,
        description="Run stringtie analysis",
    ),
    "tools_cutoff": NextflowParameter(
        type=typing.Optional[int],
        display_name="Tools Cutoff",
        default=None,
        description="Discard fusions identified by less than INT tools",
    ),
    "whitelist": NextflowParameter(
        type=typing.Optional[str],
        display_name="Fusion Whitelist",
        default=None,
        description="Path to fusions to add to the input of fusioninspector",
    ),
    "fastp_trim": NextflowParameter(
        type=bool,
        display_name="Fastp Trimming",
        default=None,
        description="Perform fastp trimming of reads, default: false",
    ),
    "trim_tail": NextflowParameter(
        type=typing.Optional[int],
        display_name="Tail Trimming",
        default=None,
        description="Perform tail trimming of reads, default: null",
    ),
    "adapter_fasta": NextflowParameter(
        type=typing.Optional[str],
        display_name="Adapter FASTA",
        default=None,
        description="Path to adapter fasta file: default: []",
    ),
    "cram": NextflowParameter(
        type=typing.Optional[str],
        display_name="CRAM Compression",
        default=None,
        description="List of tools for which to compress BAM file to CRAM, default: [], options: arriba, starfusion. Leave no space between options",
    ),
    "genome": NextflowParameter(
        type=typing.Optional[str],
        display_name="iGenomes Reference",
        default=None,
        description="Name of iGenomes reference.",
    ),
    "fasta": NextflowParameter(
        type=typing.Optional[LatchFile],
        display_name="FASTA Genome File",
        default=None,
        description="Path to FASTA genome file.",
    ),
    "fai": NextflowParameter(
        type=typing.Optional[LatchFile],
        display_name="FASTA Index File",
        default=None,
        description="Path to FASTA genome index file.",
    ),
    "gtf": NextflowParameter(
        type=typing.Optional[LatchFile],
        display_name="GTF File",
        default=None,
        description="Path to GTF genome file.",
    ),
    "chrgtf": NextflowParameter(
        type=typing.Optional[LatchFile],
        display_name="Chromosome GTF File",
        default=None,
        description="Path to chromosome GTF genome file.",
    ),
    "transcript": NextflowParameter(
        type=typing.Optional[LatchFile],
        display_name="Transcript File",
        default=None,
        description="Path to transcript file.",
    ),
    "refflat": NextflowParameter(
        type=typing.Optional[LatchFile],
        display_name="RefFlat File",
        default=None,
        description="Path to RefFlat file.",
    ),
    "rrna_intervals": NextflowParameter(
        type=typing.Optional[LatchFile],
        display_name="rRNA Intervals",
        default=None,
        description="Path to ribosomal interval list.",
    ),
    "multiqc_methods_description": NextflowParameter(
        type=typing.Optional[str],
        display_name="MultiQC Methods Description",
        default=None,
        description="Custom MultiQC yaml file containing HTML including a methods description.",
    ),
    "skip_qc": NextflowParameter(
        type=bool,
        display_name="Skip QC Steps",
        default=None,
        description="Skip QC steps",
    ),
    "skip_vis": NextflowParameter(
        type=bool,
        display_name="Skip Visualization Steps",
        default=None,
        description="Skip visualisation steps",
    ),
}
